### PR TITLE
Adds pointer input device extension

### PR DESCRIPTION
**Pull request by cosminstirbu**
## Change list

Enable AppiumDriver to perform W3CWebDriver Actions and implement support for additional pointer interaction attributes such as pressure, twist, tilt etc.
 
## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Integration tests
- [x] Have you provided integration tests to pass against the latest version of appium? (for Bugfix or New feature)

## Details

I've brought these changes from https://github.com/timotiusmargo/appium-dotnet-driver/pull/1.
Also the integration tests were brought from https://github.com/Microsoft/WinAppDriver/tree/master/Samples/C%23/StickyNotesTest

We needed these changes in order to tap on a specific coordinate in our test for our UWP application.
More details can be found here - https://github.com/Microsoft/WinAppDriver/issues/229

I admit I'm not too familiar with the overall design of this feature, so probably it makes sense to reach out to the guys at Microsoft, for any further information.

I'd like to bring this into the main repository, so we can get rid of our own fork and local .dll.

### CODE REVIEW

**Comment by cosminstirbu** [comment]
@timotiusmargo - I've cherry picked your changes from https://github.com/timotiusmargo/appium-dotnet-driver/pull/1

If you are happy with this, I'd appreciate it if you could sign the Contributor License Agreement as per @jsf-clabot.

**Comment by KazuCocoa** [comment]
@timotiusmargo Hi, could you take a look at https://github.com/appium/appium-dotnet-driver/pull/315#issuecomment-468664700 if you have a chance?

**Comment by cosminstirbu** [comment]
@KazuCocoa  & @akinsolb 

Worst case scenario, if @timotiusmargo  is unavailable to accept the Contributor License Agreement I can rebase the commits and change his commit author to myself.

Not sure if this violates any license stuff, or copywriting :-? (I'd say that shouldn't be the case)

**Comment by KazuCocoa** [comment]
personally, I would leave his credit in somewhere to respect the code.
So, if he has no response, then what about leaving his credit as a commit message and release note?

**Comment by akinsolb** [comment]
> personally, I would leave his credit in somewhere to respect the code.
> So, if he has no response, then what about leaving his credit as a commit message and release note?

Sounds reasonable, @cosminstirbu If you're happy to do this can you add the release note for this feature by updating the .csproj file?

**Comment by cosminstirbu** [comment]
I've made the changes to the cherry picked commit and the release notes to reflect @timotiusmargo's credit.

**Comment by akinsolb** [comment]
@cosminstirbu just noticed there's a typo on the Interactions folder, for example 
`src/Appium.Net/Appium/Interations/InteractionInfo.cs`
should be:
`src/Appium.Net/Appium/Interactions/InteractionInfo.cs`

**Comment by cosminstirbu** [comment]
Goo catch! I've fixed the typo.

**Comment by timotiusmargo** [comment]
Hello all! Sorry this completely slipped under my radar. Thanks for leaving me the credit for my code!

**Pull request merged**
