### PR TITLE
Configure CI for appium dotnet client

### PR DESCRIPTION
**Pull request by akinsolb**
## Change list

Add .travis.yml
 
## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Add .travis.yml to complete initial CI setup of the client.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
doesn't travis have windows nodes? I assume people usually run C# on Windows rather than on osx

**Comment by mykola-mokhnach** [comment]
Does this PR also include https://github.com/appium/appium-dotnet-driver/pull/244 ?

**Comment by akinsolb** [comment]
@mykola-mokhnach As far as I can see from the Travis documentation, it only builds against linux or OS X for C# projects. I've come across this: https://github.com/trailsjs/trails/issues/110 but I'm yet to test in 2018.
Also, thats the second time I've done that today. I can revert #244 from this PR

**Comment by akinsolb** [comment]
@mykola-mokhnach It is arguable that we should be using a CI that does run builds on Windows

**Comment by mykola-mokhnach** [comment]
Also we could probably enable [FxCop](https://msdn.microsoft.com/en-us/library/bb429476.aspx) on CI for better solution analysis.

**Comment by akinsolb** [comment]
I'll create a separate PR for enabling tests. Some existing tests are outdated and need a cleanup before adding to CI.

**Comment by mykola-mokhnach** [comment]
Ok, lets keep the other stuff for later

**Pull request merged**
