### PR TITLE
Adds IFindByTizenUIAutomation interface

### PR DESCRIPTION
**Pull request by rookiejava**
## Change list

This PR adds `IFindByTizenUIAutomation` interface and make both `TizenDriver` and `TizenElement` implement it.
 
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

This is what makes `TizenDriver`/`TizenElement` the same as other platforms such as android, iOS and Windows.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@akinsolb Can you please take a look?

**Comment by akinsolb** [comment]
@mykola-mokhnach  Looks good to me. Please merge.
@rookiejava All we need now is a Tizen app added to appium, in order to add client tests for the driver.

**Comment by mykola-mokhnach** [comment]
Can you please resolve the issue with the CLA?

**Comment by rookiejava** [comment]
As you can see in the above 2 checks passed, CLA issues have already been addressed. I don't know why @jsf-clabot's comment still exists at the top. Any help?

**Comment by mykola-mokhnach** [comment]
It performs the verification by email address. make sure the correct email address is set for you local github accoount on the machine where pull request was made

**Pull request merged**
