### PR TITLE
Get rid of converting selector to css, stop sending JS commands to get attributes

### PR DESCRIPTION
**Pull request by KazuCocoa**
## Change list

- Some methods which haven't defined by W3C spec convert selector from them to `css selector`
    - In this PR, I've changed to use id, name, class name and tag name directly.
- `GetAttribute` calls JS-command instead of calling `DriverCommand.GetElementAttribute` in W3C spec. In this PR, I've changed to call the command directly.

- related selenium client code: https://github.com/SeleniumHQ/selenium/blob/25d2e542d39768816a83931a4f43e4a006c9e78d/dotnet/src/webdriver/Remote/RemoteWebElement.cs
 
closes https://github.com/appium/appium-dotnet-driver/issues/266 and https://github.com/appium/appium-dotnet-driver/issues/265

## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

### CODE REVIEW

**Comment by akinsolb** [comment]
@KazuCocoa I had a branch for this. Will push this one at some point today

**Comment by akinsolb** [comment]
@KazuCocoa Think this should be it. I'll reformat the test project and add the tests for these in another PR.

**Comment by KazuCocoa** [comment]
thanks!

**Comment by lanzelot1989** [comment]
Thanks a lot for tackling this!

**Pull request merged**
