### PR TITLE
Location property under AppiumDriver is now expose by IHasLoaction in…

### PR DESCRIPTION
**Pull request by gravity-api**
…terface (similar as IHasSessionDetails interface)

## Change list
1. Create IHasLocation interface.
2. Implement IHasLocation interface under AppiumDriver to expose Location proerty. 
 
## Types of changes
What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] New feature (non-breaking change which adds value to the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation
- [ ] Have you proposed a file change/ PR with appium to update documentation? 
## Integration tests
- [ ] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details
It is now possible to get Location property from AppiumDriver class by extracting IHasLocation interface.

This implementation was designed to further SOLID AppiumDriver and allow a better class structure and flexibility

`
IHasLocation d = new AndroidDriver<IWebElement>(new AppiumOptions());
var lat = d.Location.Latitude;
`

### CODE REVIEW

**Comment by akinsolb** [comment]
Nice!

**Comment by akinsolb** [comment]
@gravity-api Can you add an entry explaining the change to the Changelog.md file?

**Comment by gravity-api** [comment]
done

**Comment by akinsolb** [comment]
Closes #386

**Comment by manoj9788** [comment]
Thanks @gravity-api

**Comment by gravity-api** [comment]
thank you guys, my pleasure

**Pull request merged**
