### PR TITLE
Update target framework

### PR DESCRIPTION
**Pull request by akinsolb**
## Types of changes
Update target framework to latest & last version of .net Framework v4.7.2

## Details

also facilitates #260 by supporting available & suitable runtimes on Ci servers

### CODE REVIEW

**Comment by TroyWalshProf** [comment]
Are you really sure you want/need to do this?
This will change the force users to update to 4.7.2. 
I personally am not a fan of forcing upgrades unless the is a compelling reason.

**Comment by akinsolb** [comment]
@TroyWalshProf My last thought on this was to continue targeting 4.5 as well as 4.7.2. There isn't a build server with .net 4.5

**Comment by TroyWalshProf** [comment]
The old agent does not support 4.5, but the new one does.
Here is an example:
https://github.com/TroyWalshProf/SeleniumAxeDotnet/blob/master/azure-pipelines.yml
https://dev.azure.com/AxeDotNet/Axe-Selenium-DotNet/_build?definitionId=4&_a=summary

**Comment by akinsolb** [comment]
Excellent. The new host wasn't there when I last checked.  I'll revert this and update my pipeline branch. Thanks

**Comment by TroyWalshProf** [comment]
No problem.
One quick suggestion, add build badges:
image

**Comment by akinsolb** [comment]
- [X] Status Badge.

 I'll add you as a reviewer when I make the PR

**Pull request closed without merging**
