### PR TITLE
build: Create XML documentation file on "Release" build (#441)

### PR DESCRIPTION
**Pull request by Beautyod**
Create XML documentation file on "Release" build and copy it to both binary output directories.

This is related to issue #441.
Nevertheless I'm not sure, if there is something else needed to get this XML file into the nuget package. (maybe a nuget config file entry?)

### CODE REVIEW

**Comment by akinsolb** [comment]
@Beautyod Can you sign the CLA?

**Comment by Beautyod** [comment]
@akinsolb
I don't know what you mean with CLA.

**Comment by akinsolb** [comment]
The  Contributor License Agreement. See the comment above by @jsf-clabot 

> [CLA assistant check](https://cla.js.foundation/appium/appium-dotnet-driver?pullRequest=442) 
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.js.foundation/appium/appium-dotnet-driver?pullRequest=442) before we can accept your contribution.
> 
> **Andreas Voigt** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by Beautyod** [comment]
It was somehow complicatied with the CLA, but today in the second try I could figure it out.

**Comment by akinsolb** [comment]
Glad you got it done in the end. Thanks for the contribution!

**Pull request merged**
