### PR TITLE
feat: Add support for Android Espresso's ViewMatcher

### PR DESCRIPTION
**Pull request by Redth**
## Change list

Just like Espresso's DataMatcher, adding support for ViewMatcher as well which appears to be [supported in the espresso driver](https://github.com/appium/appium-espresso-driver/pull/516).
 
## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] New feature (non-breaking change which adds value to the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation
- [ ] Have you proposed a file change/ PR with appium to update documentation? 

There is no ViewMatcher doc at all currently, though it seems to be supported in espresso driver, so not sure what C# docs would be helpful here.

## Integration tests
- [x] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details

Looking to add support for decorating some android views with automation identifiers that get set in `View.setTag(R.id.automation_id, "idvaluehere")` and using ViewMatchers to select views based on those values (ie: `onView(withTagKey(8675309,is('idvaluehere')))` with a selector such as:

```json
{
  "name" : "withTagKey",
  "args" : [ 
    8675309, 
    { 
      "name" : "is",
      "args" : "idvaluehere"
    }
  ]
}
```

### CODE REVIEW

**Review by KazuCocoa — APPROVED** [review]
seems good to me

**Comment by KazuCocoa** [comment]
Could you sign the CLA? @Redth

**Review by akinsolb — APPROVED** [review]

**Comment by Redth** [comment]
@KazuCocoa CLA signed, thanks !

**Comment by Redth** [comment]
Any idea when a release might be published with this?

**Comment by akinsolb** [comment]
Can trigger a job to release it ASAP. @Redth is it urgent?

**Comment by Redth** [comment]
@akinsolb would be helpful for some work around UI Testing infrastructure for MAUI :)

**Comment by akinsolb** [comment]
Will trigger the release today. It might take a while for it to appear in nuget due to indexing

**Pull request merged**
