### PR TITLE
#73 fix

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
- Fix of HideKeyBoard() method
- tests of hidings of keyboard.

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
Ok. I will attempt to release a new build version.

**Comment by Astro03** [comment]
Let me know if you have problems releasing it. If you can't, i can always
do it tonight.

On Mon, Jan 12, 2015 at 2:30 AM, Sergey Tikhomirov <notifications@github.com

**Comment by TikhomirovSergey** [comment]
Thanks @Astro03 ! If you can do it tonight so please release it.

**Comment by Astro03** [comment]
@TikhomirovSergey done and at  https://www.nuget.org/packages/Appium.WebDriver/

:)

**Comment by TikhomirovSergey** [comment]
@Astro03  Thank you very much! Also thanks for your developer guide here: https://github.com/appium/appium-dotnet-driver#nuget-deployment-for-maintainers

**Pull request merged**
